In [1]:
import numpy as np 
print(np.__version__)

2.3.0


In [2]:
arr_1d = np.array([1,2,3,4,5])
arr_2d = np.array([[2,3,4,5],[2,3,1,2]])
print("Array 1 d:", arr_1d)
print("Array 2d:",arr_2d)

Array 1 d: [1 2 3 4 5]
Array 2d: [[2 3 4 5]
 [2 3 1 2]]


In [3]:
py_list = [1,2,4]
print("Python list multiply by 2 " ,py_list*2)

Python list multiply by 2  [1, 2, 4, 1, 2, 4]


In [7]:
py_array = np.array([1,2,4])
print("Array Multiplication by 2 ",py_array*2)

import time 
start = time.time()
py_list = [i*2 for i in range (1000000)]
print("\nList multiplication time :", time.time() - start)

start = time.time()
py_array = np.arange(1000000)*2
print("\nNumpy multiplication time :", time.time() - start)


Array Multiplication by 2  [2 4 8]

List multiplication time : 0.05153298377990723

Numpy multiplication time : 0.0028629302978515625


## Creating the Array from scratch

## Creating the Matrix 

In [14]:
#Creating the Matrix with all element as Zero 
zero = np.zeros((2,4))
print(zero)

ones = np.ones((5,5))
print(ones)

full = np.full((2,3) ,8)
print(full)

#Random 
ran_mat = np.random.random((4 ,5))

print(ran_mat)

seq = np.arange(0,11,2)
print(seq)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[8 8 8]
 [8 8 8]]
[[0.20052733 0.20595409 0.924048   0.95126511 0.95979954]
 [0.76772567 0.15944344 0.42524076 0.25197217 0.99271439]
 [0.66961788 0.41468351 0.23941396 0.03267056 0.86292104]
 [0.96374719 0.50962266 0.68984079 0.99535233 0.15732571]]
[ 0  2  4  6  8 10]


## Vector Matrices and tensors 

In [15]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr)

m_arr  = arr.reshape(4,3)
print(m_arr)

f_arr = m_arr.flatten()
print(f_arr)

r_arr = m_arr.ravel()
print(r_arr)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
