### Numpy Array Operations 

In [1]:
import numpy as np
print(np.__version__)

2.3.0


In [6]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print("Basic Slicing :" , arr[2:7])
print("With Steps :",arr[1:8:2])
print("Negative Indexing :",arr[-2:-1])


Basic Slicing : [3 4 5 6 7]
With Steps : [2 4 6 8]
Negative Indexing : [8]


### Same operations for 2D array 

In [16]:
arr_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
print("Sepcific element:",arr_2d[1][1])
print("Entire Row :",arr_2d[0])
print("Entire Coloumn  :",arr_2d[:,1])

Sepcific element: 5
Entire Row : [1 2 3]
Entire Coloumn  : [2 5 8]


### Sorting of the array 

In [21]:
unsorted_arr = np.array([1,2,8,3,6,5,7,12,4,54,34])
print("Sorted array: ", np.sort(unsorted_arr))



Sorted array:  [ 1  2  3  4  5  6  7  8 12 34 54]


In [23]:
arr2d = np.array([[3,1] ,[2,3],[1,2]])
print("The Sorted 2d array by coloumn:", np.sort(arr2d , axis = 0))
print("The Sorted 2d array by row:", np.sort(arr2d , axis = 1))

The Sorted 2d array by coloumn: [[1 1]
 [2 2]
 [3 3]]
The Sorted 2d array by row: [[1 3]
 [2 3]
 [1 2]]


### Filtering the ARRAY 

In [26]:
numbers = np.arange(1,11)
even_Numbers = numbers[numbers%2 == 0]
print(even_Numbers)


[ 2  4  6  8 10]


### Filter with  mask

In [27]:
mask = numbers[numbers>5]
print(mask)

[ 6  7  8  9 10]


### Fancy Indexing with np.where()

In [32]:
index = [0,2,4]
print(numbers[index])
where_result = np.where(numbers>5)
print("Where_result ",where_result)
print(numbers[where_result])


[1 3 5]
Where_result  (array([5, 6, 7, 8, 9]),)
[ 6  7  8  9 10]


### condition array 


In [35]:
bool_array = np.array(numbers>5)
print(bool_array)

condition_array = np.where(numbers>5 , numbers*2 , numbers ) #It's something like np.where(if(condition) , true , false)
print(condition_array)

[False False False False False  True  True  True  True  True]
[ 1  2  3  4  5 12 14 16 18 20]


### Adding and removing DATA

In [40]:
#how to merge two arrays
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([12,23,34,45,56,67])
combined = arr1+arr2
print(combined)

concant = np.concatenate((arr1,arr2))
print(concant)


[13 25 37 49 61 73]
[ 1  2  3  4  5  6 12 23 34 45 56 67]


### Array Compatibility i.e Checking the shapes of the arrays 

a = np.array([1,2,3])
b = np.array([4,5,6 , 7])
c = np.array([7,8,9])
print("Compatibilty Shape:",a.shape == b.shape)

### Adding new Row and new Column to the 2D Array 

In [45]:
original = np.array([[1,2], [3,4]])
new_row = np.array([5,6])
with_new_row  = np.vstack((original , new_row))
print(original)
print(with_new_row)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]


In [46]:
new_col  = np.array([[2],[3]])
with_new_col = np.hstack((original , new_col))
print(with_new_col)


[[1 2 2]
 [3 4 3]]


### Deleting Element in the ARRAY

In [48]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr , 3)
print("Deleted Array :", deleted)

Deleted Array : [1 2 3 5]
